#plugin: amazon.aws.aws_ec2
#regions:
 # - eu-north-1
#keyed_groups:
 # - key: tags.Name
 #   prefix: tag
#hostnames:
 # - ip_address  # Change this from private_ip_address
#compose:
 # ansible_host: public_ip_address  # Change this from private_ip_address
#ansible_python_interpreter: /usr/bin/python3


#plugin: amazon.aws.aws_ec2
#regions:
 # - eu-north-1
#filters:
 # tag:Name:
  #  - public-instance
  #instance-state-name: running
#compose:
 # ansible_host: public_ip_address


scrape_configs:
  - job_name: 'node-exporters'
    ec2_sd_configs:
      - region: eu-north-1
        port: 9100  
        filters:
          - name: "tag:Monitoring"
            values: ["enabled"]
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: "$1:9100"


