plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1  # ✅ Tumhara AWS region
keyed_groups:
  - key: tags.Name
    prefix: tag
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address
