plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - ip_address  # Change this from private_ip_address
compose:
  ansible_host: public_ip_address  # Change this from private_ip_address
ansible_python_interpreter: /usr/bin/python3
