

plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
   instance-state-name: running
   tag:Prometheus: enabled
keyed_groups:
  - key: tags.Role
    prefix: ""
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address


 





